### PR TITLE
Spawn protection implemented

### PR DESCRIPTION
**Pull request by Lucheti29**
## Summary

Spawn protection implemented.

### CODE REVIEW

**Comment by u3games** [comment]
Nice ^^
- Missing message for "protected off".
- If player atack --> protected off.

**Comment by Lucheti29** [comment]
@u3games Good catch!

**Comment by u3games** [comment]
Perfet, only need test :)

**Comment by Lucheti29** [comment]
@u3games The test is not need it yet. It will be made it later, with all the other features.

**Pull request merged**
