### PR TITLE
Fixes from @Sacrifice78

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Lucheti29** [comment]
@Sacrifice78 I'm going to check this when i return to home. Anyway, good job!

**Comment by ghost** [comment]
At the moment (atm) It's what I've seen to start. Tomorrow i will try to check in deep. I think I've corrected the things that hurt me in sight. :+1:

**Comment by Lucheti29** [comment]
@Sacrifice78 Remember ask in Slack, it was created for that. Tag me for direct questions.

**Comment by ghost** [comment]
Okey 👍

**Pull request merged**
