### PR TITLE
Fix: NPE when the event ends and try to revive

### PR DESCRIPTION
**Pull request by Lucheti29**
## Summary
- Fix the npe caused when the event ends and try to revive a player inside the instance that doesn't exist anymore.
- Cleanup
## JAR

https://www.dropbox.com/s/9zs7cpe6m0ph8eg/PR-55%281%29.rar?dl=0

### CODE REVIEW

**Comment by u3games** [comment]
Done, nice work :+1:

**Comment by Lucheti29** [comment]
@u3games https://www.dropbox.com/s/9zs7cpe6m0ph8eg/PR-55%281%29.rar?dl=0

**Comment by fissban** [comment]
el sistema para revivir podrias ajustarlo con el nuevo sistema de sheduled q propones en tu otra rama

**Comment by Lucheti29** [comment]
@fissban Va a haber problemas de sincronización si hago eso. Por ahora opto por fixearlo así.

**Comment by u3games** [comment]
Test and work, nice fix @luksdlt92 ^^

Merger :+1:

**Pull request merged**
